"""
add_pronunciation_logs

Revision ID: 486dbabcfe88
Revises: e9e6cd17e0d7
Date: 2025-12-29 21:05:17.729424+00:00
"""

from alembic import op
import sqlalchemy as sa


revision = "486dbabcfe88"
down_revision = "e9e6cd17e0d7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pronunciation_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("word_id", sa.UUID(), nullable=False),
        sa.Column("transcribed_text", sa.String(length=500), nullable=False),
        sa.Column("expected_text", sa.String(length=255), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("feedback", sa.Text(), nullable=False),
        sa.Column("audio_duration_seconds", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("pronunciation_logs_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["word_id"],
            ["words.id"],
            name=op.f("pronunciation_logs_word_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pronunciation_logs_pkey")),
    )
    op.create_index(
        op.f("pronunciation_logs_user_id_idx"), "pronunciation_logs", ["user_id"], unique=False
    )
    op.create_index(
        op.f("pronunciation_logs_word_id_idx"), "pronunciation_logs", ["word_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("pronunciation_logs_word_id_idx"), table_name="pronunciation_logs")
    op.drop_index(op.f("pronunciation_logs_user_id_idx"), table_name="pronunciation_logs")
    op.drop_table("pronunciation_logs")
    # ### end Alembic commands ###
