"""
add_user_word_lists_table

Revision ID: 002c2d8e16b1
Revises: b02b5d92dbc9
Date: 2025-12-29 15:14:59.117041+00:00
"""

from alembic import op
import sqlalchemy as sa


revision = "002c2d8e16b1"
down_revision = "b02b5d92dbc9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_word_lists",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("word_list_id", sa.String(length=50), nullable=False),
        sa.Column("added_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("words_added", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("user_word_lists_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("user_word_lists_pkey")),
        sa.UniqueConstraint("user_id", "word_list_id", name="user_word_lists_user_list_key"),
    )
    op.create_index(
        op.f("user_word_lists_user_id_idx"), "user_word_lists", ["user_id"], unique=False
    )
    op.create_index(
        op.f("user_word_lists_word_list_id_idx"), "user_word_lists", ["word_list_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("user_word_lists_word_list_id_idx"), table_name="user_word_lists")
    op.drop_index(op.f("user_word_lists_user_id_idx"), table_name="user_word_lists")
    op.drop_table("user_word_lists")
    # ### end Alembic commands ###
