"""
add_assignments_tables

Revision ID: 21e73a4c13f7
Revises: c3d87bb3f963
Date: 2025-12-30 05:56:19.896602+00:00
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "21e73a4c13f7"
down_revision = "c3d87bb3f963"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assignments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("teacher_id", sa.UUID(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "assignment_type",
            sa.Enum("TEXT", "MULTIPLE_CHOICE", "VOICE", name="assignmenttype"),
            nullable=False,
        ),
        sa.Column("content", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PUBLISHED", "SUBMITTED", "GRADED", name="assignmentstatus"),
            nullable=False,
        ),
        sa.Column("ai_generated", sa.Boolean(), nullable=False),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["users.id"],
            name=op.f("assignments_student_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["users.id"],
            name=op.f("assignments_teacher_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("assignments_pkey")),
    )
    op.create_index(op.f("assignments_student_id_idx"), "assignments", ["student_id"], unique=False)
    op.create_index(op.f("assignments_teacher_id_idx"), "assignments", ["teacher_id"], unique=False)
    op.create_table(
        "assignment_submissions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("assignment_id", sa.UUID(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("content", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("ai_feedback", sa.Text(), nullable=True),
        sa.Column("ai_score", sa.Integer(), nullable=True),
        sa.Column("teacher_feedback", sa.Text(), nullable=True),
        sa.Column("grade", sa.Integer(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("graded_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["assignment_id"],
            ["assignments.id"],
            name=op.f("assignment_submissions_assignment_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["users.id"],
            name=op.f("assignment_submissions_student_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("assignment_submissions_pkey")),
    )
    op.create_index(
        op.f("assignment_submissions_assignment_id_idx"),
        "assignment_submissions",
        ["assignment_id"],
        unique=False,
    )
    op.create_index(
        op.f("assignment_submissions_student_id_idx"),
        "assignment_submissions",
        ["student_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("assignment_submissions_student_id_idx"), table_name="assignment_submissions"
    )
    op.drop_index(
        op.f("assignment_submissions_assignment_id_idx"), table_name="assignment_submissions"
    )
    op.drop_table("assignment_submissions")
    op.drop_index(op.f("assignments_teacher_id_idx"), table_name="assignments")
    op.drop_index(op.f("assignments_student_id_idx"), table_name="assignments")
    op.drop_table("assignments")
    # ### end Alembic commands ###
