"""
add_srs_tables

Revision ID: e9e6cd17e0d7
Revises: 002c2d8e16b1
Date: 2025-12-29 16:07:01.123015+00:00
"""

from alembic import op
import sqlalchemy as sa


revision = "e9e6cd17e0d7"
down_revision = "002c2d8e16b1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reviews",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_word_id", sa.UUID(), nullable=False),
        sa.Column("easiness", sa.Float(), nullable=False),
        sa.Column("interval", sa.Integer(), nullable=False),
        sa.Column("repetitions", sa.Integer(), nullable=False),
        sa.Column("next_review", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_review", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_word_id"],
            ["user_words.id"],
            name=op.f("reviews_user_word_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("reviews_pkey")),
    )
    op.create_index(op.f("reviews_next_review_idx"), "reviews", ["next_review"], unique=False)
    op.create_index(op.f("reviews_user_word_id_idx"), "reviews", ["user_word_id"], unique=True)
    op.create_table(
        "review_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("review_id", sa.UUID(), nullable=False),
        sa.Column("quality", sa.Integer(), nullable=False),
        sa.Column("response_time_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["reviews.id"],
            name=op.f("review_logs_review_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("review_logs_pkey")),
    )
    op.create_index(op.f("review_logs_review_id_idx"), "review_logs", ["review_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("review_logs_review_id_idx"), table_name="review_logs")
    op.drop_table("review_logs")
    op.drop_index(op.f("reviews_user_word_id_idx"), table_name="reviews")
    op.drop_index(op.f("reviews_next_review_idx"), table_name="reviews")
    op.drop_table("reviews")
    # ### end Alembic commands ###
