"""
add_audio_source_to_words

Revision ID: 9c0f34667ceb
Revises: 486dbabcfe88
Date: 2025-12-29 22:00:30.205622+00:00
"""

from alembic import op
import sqlalchemy as sa


revision = "9c0f34667ceb"
down_revision = "486dbabcfe88"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("words", sa.Column("audio_source", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("words", "audio_source")
    # ### end Alembic commands ###
